type ContestMarkCatalogDocumentTopElem = XmlTopElem & {
  id: XmlElem<number | null>;
  contest_id: XmlElem<number | null, ContestCatalogDocumentTopElem>;
  contest_name: XmlElem<string | null>;
  participant_id: XmlElem<number | null, ParticipantCatalogDocumentTopElem>;
  person_id: XmlElem<number | null, CollaboratorCatalogDocumentTopElem>;
  person_fullname: XmlElem<string | null>;
  person_position_name: XmlElem<string | null>;
  status_id: XmlElem<string | null, typeof common.participant_states>;
  general_mark: XmlElem<string | null>;
  judge_id: XmlElem<number | null, CollaboratorCatalogDocumentTopElem>;
  value: XmlElem<string | null>;
  rating: XmlElem<number | null>;
  place: XmlElem<number | null>;
  modification_date: XmlElem<Date | null>;
  app_instance_id: XmlElem<string | null>;
  MatchDocTypeExt(): void;
  OnBuildExt(): void;
  OnDeleteExt(): void;
};
