type StatisticDataCatalogDocumentTopElem = XmlTopElem & {
  id: XmlElem<number | null>;
  statistic_rec_id: XmlElem<number | null, StatisticRecCatalogDocumentTopElem>;
  budget_period_id: XmlElem<number | null, BudgetPeriodCatalogDocumentTopElem>;
  object_type: XmlElem<string | null, typeof common.exchange_object_types>;
  object_id: XmlElem<number | null>;
  object_name: XmlElem<string | null>;
  value: XmlElem<number | null>;
  value_str: XmlElem<string | null>;
  value_date: XmlElem<Date | null>;
  statistic_date: XmlElem<Date | null>;
  additinal_info: XmlElem<string | null>;
  period_type: XmlElem<string | null, typeof common.perioditys>;
  period_minute: XmlElem<number | null>;
  period_hour: XmlElem<number | null>;
  period_day: XmlElem<number | null>;
  period_month: XmlElem<number | null>;
  period_quarter: XmlElem<number | null>;
  period_year: XmlElem<number | null>;
  creation_date: XmlElem<Date | null>;
  modification_date: XmlElem<Date | null>;
  app_instance_id: XmlElem<string | null>;
  OnBuild(): void;
};
