type EducationPlanCatalogDocumentTopElem = XmlTopElem &
AdminAccessBase & {
  id: XmlElem<number | null>;
  code: XmlElem<string | null>;
  name: XmlElem<string | null>;
  group_id: XmlElem<number | null, GroupCatalogDocumentTopElem>;
  compound_program_id: XmlElem<number | null, CompoundProgramCatalogDocumentTopElem>;
  type: XmlElem<string | null, typeof common.exchange_object_types>;
  person_id: XmlElem<number | null, CollaboratorCatalogDocumentTopElem>;
  object_id: XmlElem<number | null>;
  object_name: XmlElem<string | null>;
  person_fullname: XmlElem<string | null>;
  person_org_name: XmlElem<string | null>;
  event_id: XmlElem<number | null, EventCatalogDocumentTopElem>;
  update_status_and_activity: XmlElem<boolean>;
  create_date: XmlElem<Date | null>;
  finish_date: XmlElem<Date | null>;
  fact_finish_date: XmlElem<Date | null>;
  plan_date: XmlElem<Date | null>;
  last_activity_date: XmlElem<Date | null>;
  mark: XmlElem<number | null>;
  state_id: XmlElem<number, typeof common.education_learning_states>;
  readiness_percent: XmlElem<number | null>;
  development_plan_id: XmlElem<number | null, DevelopmentPlanCatalogDocumentTopElem>;
  budget_period_id: XmlElem<number | null, BudgetPeriodCatalogDocumentTopElem>;
  assessment_appraise_id: XmlElem<number | null, AssessmentAppraiseCatalogDocumentTopElem>;
  modification_date: XmlElem<Date | null>;
  app_instance_id: XmlElem<string | null>;
  OnBuild(): void;
};
