type SaleContractCatalogDocumentTopElem = XmlTopElem &
AdminAccessBase & {
  id: XmlElem<number | null>;
  code: XmlElem<string | null>;
  name: XmlElem<string | null>;
  state_id: XmlElem<number | null, ContractStateCatalogDocumentTopElem>;
  is_agent_contract: XmlElem<boolean | null>;
  agent_org_id: XmlElem<number | null, OrgCatalogDocumentTopElem>;
  org_id: XmlElem<number | null, OrgCatalogDocumentTopElem>;
  client_org_id: XmlElem<number | null, OrgCatalogDocumentTopElem>;
  client_manager_id: XmlElem<number | null, CollaboratorCatalogDocumentTopElem>;
  manager_id: XmlElem<number | null, CollaboratorCatalogDocumentTopElem>;
  parent_sale_contract_id: XmlElem<number | null, SaleContractCatalogDocumentTopElem>;
  number: XmlElem<string | null>;
  serial_number: XmlElem<string | null>;
  date_signature: XmlElem<Date | null>;
  finish_date: XmlElem<Date | null>;
  client_legal: XmlElem<string | null>;
  provider_legal: XmlElem<string | null>;
  client_legal_name: XmlElem<string | null>;
  provider_legal_name: XmlElem<string | null>;
  bad_debt: XmlElem<boolean | null>;
  contract_cost: XmlElem<number | null>;
  currency_type_id: XmlElem<string | null, typeof lists.currency_types>;
  contract_signature: XmlElem<string | null>;
  prev_contract_id: XmlElem<number | null, SaleContractCatalogDocumentTopElem>;
  contract_type: XmlElem<number | null, SaleContractTypeCatalogDocumentTopElem>;
  sent_date: XmlElem<Date | null>;
  recipient: XmlElem<string | null>;
  consignment_document_number: XmlElem<string | null>;
  is_received: XmlElem<boolean | null>;
  received_date: XmlElem<Date | null>;
  docs_comment: XmlElem<string | null>;
  creation_date: XmlElem<Date | null>;
  modification_date: XmlElem<Date | null>;
  app_instance_id: XmlElem<string | null>;
  OnBuild(): void;
};
