type LearningRecordCatalogDocumentTopElem = XmlTopElem &
AdminAccessBase & {
  id: XmlElem<number | null>;
  code: XmlElem<string | null>;
  object_type: XmlElem<string, typeof common.exchange_object_types>;
  object_id: XmlElem<number | null>;
  object_name: XmlElem<string | null>;
  event_id: XmlElem<number | null, EventCatalogDocumentTopElem>;
  proctoring_object_type: XmlElem<string, typeof common.exchange_object_types>;
  proctoring_object_id: XmlElem<number | null>;
  proctoring_object_name: XmlElem<string | null>;
  proctoring_system_id: XmlElem<number | null, ProctoringSystemCatalogDocumentTopElem>;
  person_id: XmlElem<number | null, CollaboratorCatalogDocumentTopElem>;
  person_fullname: XmlElem<string | null>;
  person_position_name: XmlElem<string | null>;
  person_subdivision_name: XmlElem<string | null>;
  create_date: XmlElem<Date | null>;
  state_id: XmlElem<string | null, typeof common.learning_record_statuss>;
  start_date: XmlElem<Date | null>;
  finish_date: XmlElem<Date | null>;
  is_finish_record: XmlElem<boolean>;
  num_failed_checked_foto: XmlElem<number | null>;
  check_foto_state_id: XmlElem<string | null, typeof common.learning_record_statuss>;
  download_materials: XmlElem<boolean>;
  active_session_id: XmlElem<string | null>;
  active_session_finish_date: XmlElem<Date | null>;
  proctors_id: XmlMultiElemObject<number | null, CollaboratorCatalogDocumentTopElem>;
  archive_proctors_id: XmlMultiElemObject<number | null, CollaboratorCatalogDocumentTopElem>;
  is_prefer_proctor: XmlElem<boolean>;
  modification_date: XmlElem<Date | null>;
  app_instance_id: XmlElem<string | null>;
  OnBuild(): void;
};
