type LicenseCatalogDocumentTopElem = XmlTopElem & {
  id: XmlElem<number | null>;
  code: XmlElem<string | null>;
  name: XmlElem<string | null>;
  object_id: XmlElem<number | null>;
  object_type: XmlElem<string | null, typeof common.exchange_object_types>;
  object_name: XmlElem<string | null>;
  computer_name: XmlElem<string | null>;
  domain_name: XmlElem<string | null>;
  domain_short_name: XmlElem<string | null>;
  user_name: XmlElem<string | null>;
  is_temporary: XmlElem<boolean>;
  status_id: XmlElem<string | null, typeof common.status_in_knowledge_map_types>;
  sale_contract_id: XmlElem<number | null, SaleContractCatalogDocumentTopElem>;
  start_date: XmlElem<Date | null>;
  finish_date: XmlElem<Date | null>;
  maintaince_date: XmlElem<Date | null>;
  users_num: XmlElem<number | null>;
  demo: XmlElem<boolean>;
  modification_date: XmlElem<Date | null>;
  app_instance_id: XmlElem<string | null>;
  OnBuild(): void;
};
