type CompoundProgramEducationMethodCatalogDocumentTopElem = XmlTopElem & {
  id: XmlElem<number>;
  program_id: XmlElem<number>;
  parent_progpam_id: XmlElem<number>;
  position: XmlElem<number>;
  compound_program_id: XmlElem<number, CompoundProgramCatalogDocumentTopElem>;
  name: XmlElem<string>;
  education_method_id: XmlElem<number, EducationMethodCatalogDocumentTopElem>;
  education_method_name: XmlElem<string>;
  cost: XmlElem<number>;
  currency: XmlElem<string, typeof lists.currency_types>;
  cost_type: XmlElem<string, typeof common.cost_types>;
  duration: XmlElem<number>;
  person_num: XmlElem<number>;
  type: XmlElem<string, typeof common.education_method_types>;
  object_type: XmlElem<string>;
  object_id: XmlElem<number>;
  object_name: XmlElem<string>;
  object_code: XmlElem<string>;
  is_open: XmlElem<boolean>;
  duration_days: XmlElem<number>;
  MatchDocTypeExt(): void;
  OnBuildExt(): void;
  OnDeleteExt(): void;
};
