type ClosingDocumentCatalogDocumentTopElem = XmlTopElem & {
  id: XmlElem<number | null>;
  code: XmlElem<string | null>;
  name: XmlElem<string | null>;
  pay_stage_id: XmlElem<number | null, PayStageCatalogDocumentTopElem>;
  type_id: XmlElem<string | null, typeof common.payment_types>;
  cost: XmlElem<number | null>;
  currency_type_id: XmlElem<string | null, typeof lists.currency_types>;
  number: XmlElem<string | null>;
  expense_create_date: XmlElem<Date | null>;
  is_formed: XmlElem<boolean | null>;
  sent_date: XmlElem<Date | null>;
  recipient: XmlElem<string | null>;
  consignment_document_number: XmlElem<string | null>;
  is_received: XmlElem<boolean | null>;
  receiving_status_id: XmlElem<number | null, ClosingDocumentStatusCatalogDocumentTopElem>;
  received_date: XmlElem<Date | null>;
  docs_comment: XmlElem<string | null>;
  modification_date: XmlElem<Date | null>;
  app_instance_id: XmlElem<string | null>;
  OnBuild(): void;
};
