type CollaboratorCatalogDocumentTopElem = XmlTopElem & {
  id: XmlElem<number | null>;
  code: XmlElem<string | null>;
  fullname: XmlElem<string | null>;
  login: XmlElem<string | null>;
  short_login: XmlElem<string | null>;
  lowercase_login: XmlElem<string | null>;
  email: XmlElem<string | null>;
  phone: XmlElem<string | null>;
  mobile_phone: XmlElem<string | null>;
  birth_date: XmlElem<Date | null>;
  sex: XmlElem<string | null>;
  pict_url: XmlElem<string | null>;
  position_id: XmlElem<number | null, PositionCatalogDocumentTopElem>;
  position_name: XmlElem<string | null>;
  position_parent_id: XmlElem<number | null, SubdivisionCatalogDocumentTopElem>;
  position_parent_name: XmlElem<string | null>;
  org_id: XmlElem<number | null, OrgCatalogDocumentTopElem>;
  org_name: XmlElem<string | null>;
  place_id: XmlElem<number | null, PlaceCatalogDocumentTopElem>;
  region_id: XmlElem<number | null, RegionCatalogDocumentTopElem>;
  category_id: XmlMultiElemObject<string | null, CategoryCatalogDocumentTopElem>;
  web_banned: XmlElem<boolean>;
  is_arm_admin: XmlElem<boolean>;
  is_content_admin: XmlElem<boolean>;
  is_application_admin: XmlElem<boolean>;
  role_id: XmlElem<string | null, AccessRoleCatalogDocumentTopElem>;
  is_candidate: XmlElem<boolean>;
  candidate_status_type_id: XmlElem<number | null, CandidateStatusTypeCatalogDocumentTopElem>;
  candidate_id: XmlElem<number | null>;
  is_outstaff: XmlElem<boolean>;
  is_dismiss: XmlElem<boolean>;
  position_date: XmlElem<Date | null>;
  hire_date: XmlElem<Date | null>;
  dismiss_date: XmlElem<Date | null>;
  in_request_black_list: XmlElem<boolean>;
  allow_personal_chat_request: XmlElem<boolean>;
  level_id: XmlElem<number | null, LevelCatalogDocumentTopElem>;
  grade_id: XmlElem<number | null, GradeCatalogDocumentTopElem>;
  birth_date_rest_days_num(): number | null;
  knowledge_parts: XmlElem<string | null>;
  tags: XmlElem<string | null>;
  experts: XmlElem<string | null>;
  person_object_profile_id: XmlMultiElemObject<number | null, PersonObjectProfileCatalogDocumentTopElem>;
  current_state: XmlElem<string | null>;
  next_state_date: XmlElem<Date | null>;
  development_potential_id: XmlElem<number | null, DevelopmentPotentialCatalogDocumentTopElem>;
  efficiency_estimation_id: XmlElem<number | null, EfficiencyEstimationCatalogDocumentTopElem>;
  consent_kedo: XmlElem<boolean>;
  consent_kedo_date: XmlElem<Date | null>;
  provider_legal_id: XmlElem<string | null>;
  snils: XmlElem<string | null>;
  cost_center_id: XmlElem<number | null, CostCenterCatalogDocumentTopElem>;
  disp_birthdate: XmlElem<boolean>;
  disp_birthdate_year: XmlElem<boolean>;
  modification_date: XmlElem<Date | null>;
  app_instance_id: XmlElem<string | null>;
  OnBuild(): void;
};
