type CollaboratorCatalogDocumentTopElem = XmlTopElem & {
  id: XmlElem<number>;
  code: XmlElem<string>;
  fullname: XmlElem<string>;
  login: XmlElem<string>;
  short_login: XmlElem<string>;
  lowercase_login: XmlElem<string>;
  email: XmlElem<string>;
  phone: XmlElem<string>;
  mobile_phone: XmlElem<string>;
  birth_date: XmlElem<Date>;
  sex: XmlElem<string>;
  pict_url: XmlElem<string>;
  position_id: XmlElem<number, PositionCatalogDocumentTopElem>;
  position_name: XmlElem<string>;
  position_parent_id: XmlElem<number, SubdivisionCatalogDocumentTopElem>;
  position_parent_name: XmlElem<string>;
  org_id: XmlElem<number, OrgCatalogDocumentTopElem>;
  org_name: XmlElem<string>;
  place_id: XmlElem<number, PlaceCatalogDocumentTopElem>;
  region_id: XmlElem<number, RegionCatalogDocumentTopElem>;
  category_id: XmlMultiElemObject<string, CategoryCatalogDocumentTopElem>;
  web_banned: XmlElem<boolean>;
  is_arm_admin: XmlElem<boolean>;
  is_content_admin: XmlElem<boolean>;
  is_application_admin: XmlElem<boolean>;
  role_id: XmlElem<string, AccessRoleCatalogDocumentTopElem>;
  is_candidate: XmlElem<boolean>;
  candidate_status_type_id: XmlElem<number, CandidateStatusTypeCatalogDocumentTopElem>;
  candidate_id: XmlElem<number>;
  is_outstaff: XmlElem<boolean>;
  is_dismiss: XmlElem<boolean>;
  position_date: XmlElem<Date>;
  hire_date: XmlElem<Date>;
  dismiss_date: XmlElem<Date>;
  in_request_black_list: XmlElem<boolean>;
  allow_personal_chat_request: XmlElem<boolean>;
  level_id: XmlElem<number, LevelCatalogDocumentTopElem>;
  grade_id: XmlElem<number, GradeCatalogDocumentTopElem>;
  birth_date_rest_days_num(): unknown;
  knowledge_parts: XmlElem<string>;
  tags: XmlElem<string>;
  experts: XmlElem<string>;
  person_object_profile_id: XmlMultiElemObject<number, PersonObjectProfileCatalogDocumentTopElem>;
  current_state: XmlElem<string>;
  next_state_date: XmlElem<Date>;
  development_potential_id: XmlElem<number, DevelopmentPotentialCatalogDocumentTopElem>;
  efficiency_estimation_id: XmlElem<number, EfficiencyEstimationCatalogDocumentTopElem>;
  consent_kedo: XmlElem<boolean>;
  consent_kedo_date: XmlElem<Date>;
  provider_legal_id: XmlElem<string>;
  snils: XmlElem<string>;
  cost_center_id: XmlElem<number, CostCenterCatalogDocumentTopElem>;
  modification_date: XmlElem<Date>;
  app_instance_id: XmlElem<string>;
  OnBuild(): void;
};
