type ResumeCatalogDocumentTopElem = XmlTopElem &
AdminAccessBase & {
  id: XmlElem<number | null>;
  code: XmlElem<string | null>;
  name: XmlElem<string | null>;
  sex: XmlElem<string | null>;
  email: XmlElem<string | null>;
  family_status: XmlElem<string | null>;
  birth_date: XmlElem<Date | null>;
  person_id: XmlElem<number | null, CollaboratorCatalogDocumentTopElem>;
  person_fullname: XmlElem<string | null>;
  person_org_name: XmlElem<string | null>;
  person_subdivision: XmlElem<string | null>;
  person_position: XmlElem<string | null>;
  creator_person_id: XmlElem<number | null, CollaboratorCatalogDocumentTopElem>;
  creator_person_fullname: XmlElem<string | null>;
  forbid_portal_delete: XmlElem<boolean>;
  filling_type: XmlElem<string>;
  min_wage: XmlElem<number | null>;
  max_wage: XmlElem<number | null>;
  currency_type_id: XmlElem<string | null, typeof lists.currency_types>;
  profession_id: XmlElem<number | null, ProfessionalAreaCatalogDocumentTopElem>;
  profession_area_id: XmlElem<string | null, typeof lists.professional_areas>;
  profession_area: XmlElem<string | null>;
  region_id: XmlElem<number | null, RegionCatalogDocumentTopElem>;
  employment_type_id: XmlElem<string | null, typeof common.employment_types>;
  schedule_work_id: XmlElem<string | null, typeof common.employment_kinds>;
  schedule_id: XmlElem<number | null, WorkScheduleCatalogDocumentTopElem>;
  vacancy_source_id: XmlElem<number | null, VacancySourceCatalogDocumentTopElem>;
  exp_years: XmlElem<number | null>;
  willingness_travel_type_id: XmlElem<string | null, typeof common.willingness_travel_types>;
  is_willing_relocate: XmlElem<boolean>;
  main_educ_type_id: XmlElem<string | null, typeof common.educ_types>;
  education: XmlElem<string | null>;
  is_archive: XmlElem<boolean>;
  is_candidate: XmlElem<boolean>;
  lng_id: XmlMultiElemObject<string | null, typeof common.languages>;
  educ_type_id: XmlMultiElemObject<string | null, typeof common.expended_educ_types>;
  education_type_id: XmlElem<number | null, EducationTypeCatalogDocumentTopElem>;
  creation_date: XmlElem<Date | null>;
  modification_date: XmlElem<Date | null>;
  app_instance_id: XmlElem<string | null>;
  OnBuild(): void;
};
