type CareerReserveTutorCatalogDocumentTopElem = XmlTopElem & {
  id: XmlElem<number | null>;
  career_reserve_id: XmlElem<number | null, CareerReserveCatalogDocumentTopElem>;
  start_date: XmlElem<Date | null>;
  plan_readiness_date: XmlElem<Date | null>;
  finish_date: XmlElem<Date | null>;
  readiness_percent: XmlElem<number | null>;
  code: XmlElem<string | null>;
  name: XmlElem<string | null>;
  status: XmlElem<string | null, typeof common.career_reserve_status_types>;
  person_id: XmlElem<number | null, CollaboratorCatalogDocumentTopElem>;
  person_fullname: XmlElem<string | null>;
  tutor_id: XmlElem<number | null, CollaboratorCatalogDocumentTopElem>;
  tutor_type: XmlElem<string>;
  is_responsible: XmlElem<boolean>;
  tutor_fullname: XmlElem<string | null>;
  MatchDocTypeExt(): void;
  OnBuildExt(): void;
  OnDeleteExt(): void;
};
