declare namespace tools_cl {
  let generic_folder_prefix: XmlElem<string>;
  function html_decode(sSourceHTML_PARAM: string): unknown;
  function is_true_cl(sValue: string): unknown;
  function resource_tag(iResourseIDPARAM: number, sFileNAmePARAM: string): unknown;
  function imprint(sSource: string): unknown;
  function convertToB62(iNumber: number): unknown;
  function recursive_copy_url(sSourceURL_PARAM: string, sDestURL_PARAM: string): unknown;
  function reveal_riches(sTextPARAM: string): unknown;
  let xsl_assembly: XmlElem<unknown>;
  function xsl_transform(xslString: unknown, xmlString: unknown, aParams: unknown): unknown;
  function lexicise_it(_sSourcePARAM: unknown, _bInversePARAM: unknown): unknown;
  function polska_functzia(_sSourcePARAM: unknown, _bIsPostfixPARAM: unknown): unknown;
  function transform_event(oEventXML_PARAM: unknown, sEventNode_PARAM: string): unknown;
  function convertHTML2BB(sHTML: string): unknown;
  function convertBB2HTML(sBB: string): unknown;
  function xmlSubstituteConsts(xmlData: unknown, path: unknown, aConsts: unknown, prefix: unknown, bUseShared: boolean, iLocalizationID: number, courseIDPARAM: unknown): unknown;
  function search_dupe_const(courseIDPARAM: unknown, localizationIDPARAM: unknown, text: string): unknown;
  function get_object(vIdentifierPARAM: unknown, bOpenDocPARAM: boolean): unknown;
  function process_resources(sSourcePARAM: string, sMakeMyPrefix: string, oRegExpObjectPARAM: unknown, xarrMyResources_PARAM: unknown, bResourceImbuePARAM: boolean, bOverwritePARAM: boolean, docRepositorium_TARGET: unknown, curUserIDPARAM: unknown, teUserPARAM: unknown, sCodeIdentifierPARAM: string, sFileUrlPARAM: string): unknown;
  function i_get_my_roleid(curUserIDPARAM: unknown, teUserPARAM: unknown): unknown;
  function is_author_of_type(vCoursePARAM: unknown, iUserIDPARAM: number, iTypePARAM: number): unknown;
  let log_obj: XmlElem<unknown>;
  function log_cl_create(): unknown;
  function log_cl_log(sMSG: string): unknown;
  function get_cl_log(): unknown;
  function update_params(sParamsxml: string, sEtalonXml: string, vObjectPARAM: unknown, oOptionsPARAM: unknown): unknown;
  function param_update_constants(xmlParam: unknown, sPathPARAM: string, slideIDPARAM: unknown, frameIDPARAM: unknown, slideObjectIDPARAM: unknown, courseIDPARAM: unknown, localizationIDPARAM: unknown, bUseSharedPARAM: boolean): unknown;
  function get_constant_by_tag(sTextPARAM: string, objectIDPARAM: unknown): unknown;
  function create_constant(sTextPARAM: string, objectIDPARAM: unknown, objectCatalogPARAM: unknown, localizationIDPARAM: unknown, oTypePARAM: unknown, originalValuePARAM: unknown, sSuggestedCodePARAM: string): unknown;
  function obtain_constant(sConstantCode: string, localizationIDPARAM: unknown, localizationValuePARAM: unknown, objectIDPARAM: unknown, objectCatalogPARAM: unknown, oFlags: unknown): unknown;
  function build_constant_prefix(sSlideID: number, sFrameID: number, sObjectID: number): unknown;
  function summon_constants(iObjectIDPARAM: number, sTextDataPARAM: string, iLocIDPARAM: number): unknown;
  function summon_aux_const(CoursePARAM: unknown, paramPARAM: unknown, iLocIDPARAM: number): unknown;
  function export_scorm(iCLCourseID_PARAM: number, curUserIDPARAM: unknown, iLocIDPARAM: number, paramsZipUrl: unknown): unknown;
  function build_wcl_back(iCLCourseID_PARAM: number): unknown;
  function build_object_xml(iClObjID_PARAM: number, sWTD_PARAM: string): unknown;
  function build_shape_xml(iClShapeID_PARAM: number): unknown;
  function build_module_xml_back(iClModuleID_PARAM: number): unknown;
  function build_slide_xml_back(iClSlideID_PARAM: number): unknown;
  function build_object_in_slide_xml(fldObjectElemPARAM: unknown, bDesignTime: boolean, locIDPARAM: unknown, courseIDPARAM: unknown): unknown;
  function load_slide_from_xml_object(xmlSlide: unknown, sCourseCodePARAM: string, iModuleID_PARAM: number, iCourseID_PARAM: number, docSlide_PARAM: unknown, bTryUpdatePARAM: boolean, bTryXSlRetransform: boolean, localizationIDPARAM: unknown): unknown;
  function load_module_from_description(sWorkingDirUrlPARAM: string, xmlModuleDescriptionPARAM: unknown, sCourseCodePARAM: string, iCourseID_PARAM: number, docRepositorium_PARAM: unknown, iUserIDPARAM: number, teUserPARAM: unknown, localizationIDPARAM: unknown): unknown;
  function load_module_from_xml_object(oModuleXML_PARAM: unknown, vModule: unknown, iCourseID_PARAM: number, xmlModuleDescriptionPARAM: unknown, s_aicc_code_PARAM: unknown, bTryUpdatePARAM: boolean, bTemplate: boolean, localizationIDPARAM: unknown): unknown;
  function manual_import_course_routine(): unknown;
  function import_course_routine(sWCLUrlPARAM: string, oCourse2_PARAM: unknown, docCLCourse_PARAM: unknown, iRepositoryID_PARAM: number, iUserIDPARAM: number, teUserPARAM: unknown, localizationIDPARAM: unknown): unknown;
  function import_objects_from_list(sXmlUrlParam: string, sMode: string): unknown;
  function import_autoshape_from_folder(sFolderUrlParam: string, sLabelParam: string): unknown;
  function import_module_templates_from_folder(sFolderUrlParam: string, sLabelParam: string, localizationIDPARAM: unknown): unknown;
  function import_objects_from_folder(sFolderUrlParam: string, sLabelParam: string): unknown;
  function manual_import_objects_from_pack(sMode: string): unknown;
  function import_objects_from_pack(sFileUrlPARAM: string, sMode: string): unknown;
  function generate_runtime_xml_cache(iModuleIDParam: number, teModuleParam: unknown, curUserIDPARAM: unknown, bSplashPARAM: boolean, locIDPARAM: unknown, oAuxParams: unknown): unknown;
  function generate_runtime_xml(iModuleIDParam: number, teModuleParam: unknown, curUserIDPARAM: unknown, bSplashPARAM: boolean, locIDPARAM: unknown, oAuxParams: unknown): unknown;
  function prepare_module_deserialization(sModuleUrlPARAM: string, sCodeIdentifierPARAM: string, docRepositorium_TARGET: unknown, curUserIDPARAM: unknown, teUserPARAM: unknown, bOverwritePARAM: boolean): unknown;
  function eradicate_slide(docCLSlidePARAM: unknown): unknown;
  function make_module_real(docCLCoursePARAM: unknown, docModuleTepmlatePARAM: unknown, docRepositorium_TARGET: unknown, curUserIDPARAM: unknown, teUserPARAM: unknown, xmlModuleDescriptionPARAM: unknown, bImmaterialSlides: boolean, localizationIDPARAM: unknown): unknown;
  function read_resource(sRTag: string, iResult: number): unknown;
  function export_constants(sObjectIDPARAM: string, iLocoSourceID: number, iLocoTargetID: number, fileUrl: unknown): unknown;
  function import_constants(teObjectPARAM: unknown, sXlsFileUrlPARAM: string): unknown;
  function convert_object_titles(iObjectIDParam: number, iLocalizationIDParam: number): unknown;
}
