
interface IWTAssessmentTopElem {
  id?: XmlElem<number>;
  code?: XmlElem<string>;
  title?: XmlElem<string>;
  name?: XmlElem<string>;
  resource_id?: XmlElem<number>;
  status?: XmlElem<string>;
  testing_system_id?: XmlElem<number>;
  duration?: XmlElem<number>;
  duration_days?: XmlElem<number>;
  attempts_num?: XmlElem<number>;
  passing_score?: XmlElem<number>;
  use_scale_calculation?: XmlElem<boolean>;
  test_finish_redirect?: XmlElem<string>;
  test_finish_redirect_url?: XmlElem<string>;
  activation_code?: XmlElem<string>;
  not_display_feedback?: XmlElem<boolean>;
  not_disp_last_attempt?: XmlElem<boolean>;
  not_display_unfinished_score?: XmlElem<boolean>;
  feedback_wrong?: XmlElem<string>;
  feedback_correct?: XmlElem<string>;
  feedback_passed?: XmlElem<string>;
  feedback_failed?: XmlElem<string>;
  use_launch_code?: XmlElem<boolean>;
  not_sent_correct_answer?: XmlElem<boolean>;
  sections?: XmlMultiElem<IWTAssessmentSection>;
  certificate_type_id?: XmlElem<number>;
  display_result?: XmlElem<boolean>;
  is_adaptive_test?: XmlElem<boolean>;
  display_correct_answer?: XmlElem<boolean>;
  display_result_report?: XmlElem<boolean>;
  is_open?: XmlElem<boolean>;
  display_correct_answer_in_report?: XmlElem<boolean>;
  display_answers_in_report?: XmlElem<boolean>;
  proctoring_system_id?: XmlElem<number>;
  external_type?: XmlElem<string>;
  not_use_default_notification?: XmlElem<boolean>;
  comment?: XmlElem<string>;
  publish_url?: XmlElem<string>;
  publish_date?: XmlElem<Date>;
  template_url?: XmlElem<string>;
  win_width?: XmlElem<string>;
  win_height?: XmlElem<string>;
  before_finish_eval?: XmlElem<string>;
  desc?: XmlElem<string>;
  get_info?(): Object;
  update_structure?(): boolean;
}

type IWTAssessmentDocument = IWTXmlDocument<IWTAssessmentTopElem>;
