type TaskCatalogDocumentTopElem = XmlTopElem &
AdminAccessBase & {
  id: XmlElem<number | null>;
  code: XmlElem<string | null>;
  name: XmlElem<string | null>;
  task_type_id: XmlElem<number | null, TaskTypeCatalogDocumentTopElem>;
  parent_task_id: XmlElem<number | null, TaskCatalogDocumentTopElem>;
  translated_task_id: XmlElem<number | null, TaskCatalogDocumentTopElem>;
  translated_target_type: XmlElem<string | null, typeof common.exchange_object_types>;
  translated_target_id: XmlElem<number | null>;
  assigner_id: XmlElem<number | null, CollaboratorCatalogDocumentTopElem>;
  executor_type: XmlElem<string | null, typeof common.exchange_object_types>;
  executor_id: XmlElem<number | null>;
  status: XmlElem<string | null, typeof common.task_statuses>;
  custom_state_id: XmlElem<string | null>;
  plan: XmlElem<string | null>;
  fact: XmlElem<string | null>;
  plan_value: XmlElem<number | null>;
  fact_value: XmlElem<number | null>;
  value: XmlElem<number | null>;
  readiness_percent: XmlElem<number | null>;
  priority: XmlElem<number | null>;
  source_object_type: XmlElem<string | null, typeof common.exchange_object_types>;
  source_object_id: XmlElem<number | null>;
  pay_stage_id: XmlElem<number | null, PayStageCatalogDocumentTopElem>;
  target_object_type: XmlElem<string | null, typeof common.exchange_object_types>;
  target_object_id: XmlElem<number | null>;
  fact_object_type: XmlElem<string | null, typeof common.exchange_object_types>;
  fact_object_id: XmlElem<number | null>;
  expert_id: XmlMultiElemObject<number | null, CollaboratorCatalogDocumentTopElem>;
  date_plan: XmlElem<Date | null>;
  date_fact: XmlElem<Date | null>;
  start_date_plan: XmlElem<Date | null>;
  end_date_plan: XmlElem<Date | null>;
  plan_budget_period_id: XmlElem<number | null, BudgetPeriodCatalogDocumentTopElem>;
  fact_budget_period_id: XmlElem<number | null, BudgetPeriodCatalogDocumentTopElem>;
  plan_labor_costs: XmlElem<number | null>;
  fact_labor_costs: XmlElem<number | null>;
  role_id: XmlMultiElemObject<number | null>;
  desc: XmlElem<string | null>;
  comment: XmlElem<string | null>;
  modification_date: XmlElem<Date | null>;
  app_instance_id: XmlElem<string | null>;
  workflow_id: XmlElem<number | null, WorkflowCatalogDocumentTopElem>;
  workflow_state: XmlElem<string | null>;
  workflow_state_name: XmlElem<string | null>;
  workflow_person_id: XmlMultiElemObject<number | null, CollaboratorCatalogDocumentTopElem>;
  workflow_matching_type: XmlElem<string | null>;
  conversation_id: XmlElem<number | null, ConversationCatalogDocumentTopElem>;
  preparation_id: XmlMultiElemObject<number | null, CollaboratorCatalogDocumentTopElem>;
  OnBuild(): void;
};
