declare namespace tools_report {
  function log_report(sMsg: string): unknown;
  function model_roles(curUserID: number, sApplicationID: number): unknown;
  function save_report_to_file(sHtml: string, sReportName: string, sOutType: string, sFileUrl: string, bIsWebClient: boolean, sColumns: string, arrData: unknown, oParams: unknown): unknown;
  function read_report_settings(sReportName: string, oTopElem: unknown, arrParams: unknown): unknown;
  function save_report_settings(sReportName: string, arrParams: unknown): unknown;
  function ExcelColumnsList(): unknown;
  function MaxReportVisibleRows(): unknown;
  function MaxWorksheetRows(): unknown;
  function bIsLinux(): unknown;
  function not_studied_report(oParams: unknown): unknown;
  function not_certified_report(oParams: unknown): unknown;
  function qualification_report(oParams: unknown): unknown;
  function statistic_report(_param_str: unknown): unknown;
  function policy_type_report(oParams: unknown): unknown;
  function benefit_report(oParams: unknown): unknown;
  function payment_type_report(oParams: unknown): unknown;
  function no_request_by_good_report(oParams: unknown): unknown;
  function transaction_report(oParams: unknown): unknown;
  function good_statistics_report(oParams: unknown): unknown;
  function request_statistics_report(oParams: unknown): unknown;
  function poll_report(oParams: unknown): unknown;
  function poll_procedure_report(oParams: unknown): unknown;
  function view_accounts(Ps: unknown, curUserID: number, sApplicationID: number): unknown;
  function view_badges(Ps: unknown, curUserID: number, sApplicationID: number): unknown;
  function view_awards(Ps: unknown, curUserID: number, sApplicationID: number): unknown;
  function events_report(oParams: unknown, curUser: CurUser): unknown;
  function persons_report(Ps: unknown): unknown;
  function course_part_report(oParams: unknown, curUser: CurUser): unknown;
  function exceed_course_report(oParams: unknown, curUser: CurUser): unknown;
  function question_report(oParams: unknown, curUser: CurUser): unknown;
  function test_question_report(oParams: unknown, curUser: CurUser): unknown;
  function successors_report(oParams: unknown, curUser: CurUser): unknown;
  function key_positions_protection_report(oParams: unknown, curUser: CurUser): unknown;
  function fnGetCourseVersionFromUrl(strUrlParam: string): unknown;
  function fnCreateExcelFile(oParam: unknown, fldParamFormParam: unknown, fldDataFormParam: unknown): unknown;
  function fnSaveFile(oObjectParam: unknown, sFileType: string, bClearObjectParam: boolean, sDestinationParam: string): unknown;
  function fnFindFileType(sFileUrlParam: string): unknown;
  function arrayCross(arrFirstParam: unknown, arrSecondParam: unknown): unknown;
  function getCatUser(fldLearningParam: unknown): unknown;
  function fnAddLearnings(arrLearningParam: unknown, fldParamFormParam: unknown, fldDataFormParam: unknown, oResParam: unknown): unknown;
  function fnAddTestLearnings(arrTestLearningParam: unknown, fldParamFormParam: unknown, fldDataFormParam: unknown, oResParam: unknown): unknown;
  function fnAddCareerReserves(arrLoopParam: unknown, fldParamFormParam: unknown, fldDataFormParam: unknown, oResParam: unknown): unknown;
  function course_report(Ps: unknown, curUserID: number, sApplicationID: number): unknown;
  function competence_by_depart_report(_param_str: unknown): unknown;
  function event_dep_report(_param_str: unknown, curUser: CurUser): unknown;
  function budget_report(sXmlParam: string): unknown;
  function request_report(oParams: unknown): unknown;
  function server_log_report(_param_str: unknown): unknown;
  function education_method_report(_param_str: unknown): unknown;
  function event_by_depart_report(_param_str: unknown, curUser: CurUser): unknown;
  function budget_transfers_report(): unknown;
  function course_by_depart_report(_param_str: unknown): unknown;
  function test_by_depart_report(_param_str: unknown): unknown;
  function certificate_type_report(oParams: unknown): unknown;
  function test_report(_param_str: unknown, curUserID: number, sApplicationID: number): unknown;
  function course_objectives_report(oParams: unknown): unknown;
  function course_module_report(oParams: unknown): unknown;
  function question_by_depart_report(_param_str: unknown): unknown;
  function event_person_report(_param_str: unknown, curUser: CurUser): unknown;
  function profiling_report(sXmlParam: string): unknown;
  function test_person_report(Ps: unknown): unknown;
  function educ_plan_report(Ps: unknown): unknown;
  function learning_dynamics_report(sParams: string): unknown;
  function learning_statistics_report(_param_str: unknown): unknown;
  function course_integral_efficiency_report(_param_str: unknown): unknown;
  function questions_analytics_report(_param_str: unknown): unknown;
  function course_comment_report(_param_str: unknown): unknown;
  function course_module_status_report(_param_str: unknown): unknown;
  function get_report_data(sUrlParam: string, bSwitchForm: boolean, sReportName: string): unknown;
  function career_reserve_report(_param_str: unknown): unknown;
  function run_db_perfomance_test(check_current_db: unknown, countUsers: unknown): unknown;
  function gather_system_info(): unknown;
  function get_xhttp_info(): unknown;
  function custom_report_html_export(iCustomReportID: number, teCustomReport: unknown, curUserID: number, sOutType: string): unknown;
  function custom_report_export_to_file(vCustomReport: unknown, curUserID: number, sOutType: string, sFileUrl: string): unknown;
  function list_html_export(oList: unknown, sOutType: string): unknown;
  function load_word(sHtml: string, sFileUrl: string): unknown;
  function load_excel(sHtml: string, sFileUrl: string): unknown;
  function list_export_to_file(oList: unknown, sOutType: string, sFileUrl: string): unknown;
  function recommender_detail_report(Ps: unknown): unknown;
  function recommender_use_report(_param_str: unknown): unknown;
  function recommender_compare_report(_param_str: unknown): unknown;
}
