type OutstaffOrderExecutionStageCatalogDocumentTopElem = XmlTopElem & {
  id: XmlElem<number | null>;
  outstaff_order_execution_id: XmlElem<number | null, OutstaffOrderExecutionCatalogDocumentTopElem>;
  status: XmlElem<string, typeof common.order_status_types>;
  formed_date: XmlElem<Date | null>;
  person_id: XmlElem<number | null, CollaboratorCatalogDocumentTopElem>;
  outstaff_provider_id: XmlElem<number | null, OutstaffProviderCatalogDocumentTopElem>;
  outstaff_contract_id: XmlElem<number | null, OutstaffContractCatalogDocumentTopElem>;
  outstaff_order_id: XmlElem<number | null, OutstaffContractCatalogDocumentTopElem>;
  subdivision_id: XmlElem<number | null, SubdivisionCatalogDocumentTopElem>;
  budget_period_id: XmlElem<number | null, BudgetPeriodCatalogDocumentTopElem>;
  start_date: XmlElem<Date | null>;
  finish_date: XmlElem<Date | null>;
  position_common_id: XmlElem<number | null, PositionCommonCatalogDocumentTopElem>;
  stage_id: XmlElem<string | null>;
  stage_parent_id: XmlElem<string | null>;
  stage_collaborator_id: XmlElem<number | null, CollaboratorCatalogDocumentTopElem>;
  stage_date: XmlElem<Date | null>;
  stage_fact_date: XmlElem<Date | null>;
  stage_hour_num: XmlElem<number | null>;
  stage_hours_worked: XmlElem<number | null>;
  stage_is_assist: XmlElem<boolean>;
  stage_status_type: XmlElem<string | null, typeof common.outstaff_order_execution_status_types>;
  MatchDocTypeExt(): void;
  OnBuildExt(): void;
  OnDeleteExt(): void;
};
