type RequestCatalogDocumentTopElem = XmlTopElem &
AdminAccessBase & {
  id: XmlElem<number | null>;
  code: XmlElem<string | null>;
  type: XmlElem<string | null, typeof common.exchange_object_types>;
  request_type_id: XmlElem<number | null, RequestTypeCatalogDocumentTopElem>;
  status_id: XmlElem<string, typeof common.request_status_types>;
  person_id: XmlElem<number | null, CollaboratorCatalogDocumentTopElem>;
  person_fullname: XmlElem<string | null>;
  person_org_name: XmlElem<string | null>;
  person_subdivision_name: XmlElem<string | null>;
  is_group: XmlElem<boolean>;
  person_num: XmlElem<number | null>;
  object_id: XmlElem<number | null>;
  object_name: XmlElem<string | null>;
  budget_period_id: XmlElem<number | null, BudgetPeriodCatalogDocumentTopElem>;
  workflow_id: XmlElem<number | null, WorkflowCatalogDocumentTopElem>;
  workflow_state: XmlElem<string | null>;
  workflow_state_name: XmlElem<string | null>;
  create_date: XmlElem<Date | null>;
  close_date: XmlElem<Date | null>;
  tag_id: XmlMultiElemObject<number | null, TagCatalogDocumentTopElem>;
  workflow_person_id: XmlMultiElemObject<number | null, CollaboratorCatalogDocumentTopElem>;
  workflow_matching_type: XmlElem<string | null>;
  workflow_main_person_id: XmlMultiElemObject<number | null, CollaboratorCatalogDocumentTopElem>;
  knowledge_parts: XmlElem<string | null>;
  tags: XmlElem<string | null>;
  experts: XmlElem<string | null>;
  modification_date: XmlElem<Date | null>;
  app_instance_id: XmlElem<string | null>;
  OnBuild(): void;
};
