type RequestCatalogDocumentTopElem = XmlTopElem &
AdminAccessBase & {
  id: XmlElem<number>;
  code: XmlElem<string>;
  type: XmlElem<string, typeof common.exchange_object_types>;
  request_type_id: XmlElem<number, RequestTypeCatalogDocumentTopElem>;
  status_id: XmlElem<string, typeof common.request_status_types>;
  person_id: XmlElem<number, CollaboratorCatalogDocumentTopElem>;
  person_fullname: XmlElem<string>;
  person_org_name: XmlElem<string>;
  person_subdivision_name: XmlElem<string>;
  is_group: XmlElem<boolean>;
  person_num: XmlElem<number>;
  object_id: XmlElem<number>;
  object_name: XmlElem<string>;
  budget_period_id: XmlElem<number, BudgetPeriodCatalogDocumentTopElem>;
  workflow_id: XmlElem<number, WorkflowCatalogDocumentTopElem>;
  workflow_state: XmlElem<string>;
  workflow_state_name: XmlElem<string>;
  create_date: XmlElem<Date>;
  close_date: XmlElem<Date>;
  tag_id: XmlMultiElemObject<number, TagCatalogDocumentTopElem>;
  workflow_person_id: XmlMultiElemObject<number, CollaboratorCatalogDocumentTopElem>;
  workflow_matching_type: XmlElem<string>;
  workflow_main_person_id: XmlMultiElemObject<number, CollaboratorCatalogDocumentTopElem>;
  knowledge_parts: XmlElem<string>;
  tags: XmlElem<string>;
  experts: XmlElem<string>;
  modification_date: XmlElem<Date>;
  app_instance_id: XmlElem<string>;
  OnBuild(): unknown;
};
