declare namespace tools_lp {
  function check_access_lpe(curUser: CurUser): unknown;
  function check_web_mode_link(fldLinkParam: unknown, Env: unknown): unknown;
  function check_web_mode_disp(curWebModeParam: unknown, curOverrideWebTemplateIDParam: unknown, Env: unknown): unknown;
  function fill_context(xarrStatisticRecsParam: unknown, bIsObject: boolean, Env: unknown, teWebModeParam: unknown): unknown;
  function get_context(sCatalogName: string, bIsObject: boolean, Env: unknown): unknown;
  function get_web_mode_context(teWebModeParam: unknown, Env: unknown, arrContextCodesParam: unknown): unknown;
  function substitute(sTextParam: string, Env: unknown, bLPE: boolean, bLPEPreview: boolean): unknown;
  function cleanup_locals(sTextParam: string): unknown;
  function fld_to_arr(fldParam: unknown): unknown;
  function fld_to_obj(fldParam: unknown): unknown;
  function owt_wvars_to_json(teOWT: unknown, bBasicParamsOnly: boolean): unknown;
  function plain_wvars_to_json(teDoc: unknown, bBasicParamsOnly: boolean): unknown;
  function get_vars_from_cache(teOWT: unknown): unknown;
  function get_preset(oWDParamSets: unknown, sPrefix: string, sPreset: string): unknown;
  function get_runtime_data_from_cache(teOWT: unknown, bSkipCache: boolean): unknown;
  function get_html_from_cache(teOWT: unknown, bSkipCache: boolean): unknown;
  function update_legacy_params(oParams: unknown, aNewParams: unknown): unknown;
  function refresh_web_template_cache(iWebDesignIDParam: number): unknown;
  function webcolor_to_hex(sWebColor: string): unknown;
  function hex_to_rgb(sHexColor: string, bRGBA: boolean, nOpacity: unknown): unknown;
  function any_color_to_rgb(sColor: string, bRGBA: boolean, nOpacity: unknown): unknown;
  function get_owt_params(oCurParams: unknown, aOWTParams: unknown, sPrefix: string, bUsePreset: boolean, oPreset: unknown, sOWTId: number, oArgs: unknown): unknown;
  function apply_param_type(oParam: unknown, sValue: string): unknown;
  function get_template_cache_id(iWebModeIDParam: number, iSiteIDParam: number, sLocaleParam: string): unknown;
  function save_template_cache(teWebModeParam: unknown, sTextParam: string, iSiteIDParam: number, sLocaleParam: string): unknown;
  function get_template_cache(teWebModeParam: unknown, iSiteIDParam: number, sLocaleParam: string): unknown;
  function replace_template_cache(teWebModeParam: unknown, sTextParam: string, Request: unknown): unknown;
  function replace_local_subs(oColParams: unknown): unknown;
  function map_collection_result(oColResult: unknown, aColMap: unknown): unknown;
  function fill_subs_with_values(Env: unknown, arrSubsParam: unknown): unknown;
  function substitute_in_cache(sTextParam: string, arrSubsParam: unknown, bParamsOnly: boolean): unknown;
  function collect_all_subs(sTextParam: string): unknown;
  function list_subs(oArgs: unknown): unknown;
  function map_param_name(oArgs: unknown): unknown;
  function map_item_param(oArgs: unknown): unknown;
  function get_font_css(oArgs: unknown): unknown;
  function get_workarea_css(oArgs: unknown): unknown;
  function get_font_params_array(oArgs: unknown): unknown;
  function get_block_css(oArgs: unknown): unknown;
  function set_font_vars(oArgs: unknown): unknown;
  function update_runtime_env(oArgs: unknown): unknown;
  function copy_web_mode(oSourceWebModeParam: unknown, oWebModeFieldsParam: unknown): unknown;
  function clear_template_cache(iWebDesignIDParam: number): unknown;
}
