type WebRuleCatalogDocumentTopElem = XmlTopElem & {
  id: XmlElem<number | null>;
  code: XmlElem<string | null>;
  name: XmlElem<string | null>;
  url: XmlElem<string | null>;
  is_enabled: XmlElem<boolean | null>;
  is_pattern: XmlElem<boolean | null>;
  use_matches: XmlElem<boolean | null>;
  redirect_url: XmlElem<string | null>;
  redirect_type: XmlElem<number | null>;
  redirect_web_mode_id: XmlElem<number | null, WebModeCatalogDocumentTopElem>;
  weight: XmlElem<number | null>;
  web_design_id: XmlElem<number | null, WebDesignCatalogDocumentTopElem>;
  site_id: XmlElem<number | null, SiteCatalogDocumentTopElem>;
  role_id: XmlMultiElemObject<number | null>;
  is_std: XmlElem<boolean | null>;
  changed: XmlElem<boolean>;
  modification_date: XmlElem<Date | null>;
  OnBuild(): void;
};
