type OperationCatalogDocumentTopElem = XmlTopElem & {
  id: XmlElem<number | null>;
  code: XmlElem<string | null>;
  name: XmlElem<string | null>;
  category: XmlElem<string | null>;
  operation_type: XmlElem<number | null>;
  action: XmlElem<string | null>;
  operation_catalog_list: XmlElem<string | null>;
  object_name: XmlElem<string | null, typeof common.exchange_object_types>;
  group: XmlElem<string | null>;
  is_system: XmlElem<boolean | null>;
  remote_action_id: XmlElem<number | null, RemoteActionCatalogDocumentTopElem>;
  use_script: XmlElem<boolean>;
  use_access_eval: XmlElem<boolean>;
  is_std: XmlElem<boolean>;
  changed: XmlElem<boolean>;
  priority: XmlElem<number>;
  role_id: XmlMultiElemObject<number | null>;
  modification_date: XmlElem<Date | null>;
  app_instance_id: XmlElem<string | null>;
  OnBuild(): void;
};
