type EventCatalogDocumentTopElem = XmlTopElem &
EventCatalogBase &
AdminAccessBase & {
  id: XmlElem<number>;
  is_model: XmlElem<boolean>;
  use_vclass: XmlElem<boolean>;
  vclass_setting_id: XmlElem<number, VclassSettingCatalogDocumentTopElem>;
  compound_program_id: XmlElem<number, CompoundProgramCatalogDocumentTopElem>;
  education_program_id: XmlElem<number, EducationProgramCatalogDocumentTopElem>;
  education_method_id: XmlElem<number, EducationMethodCatalogDocumentTopElem>;
  create_compound_program_id: XmlElem<number, CompoundProgramCatalogDocumentTopElem>;
  place_id: XmlElem<number, PlaceCatalogDocumentTopElem>;
  vclass_host: XmlElem<string>;
  record_exists: XmlElem<boolean>;
  show_record: XmlElem<boolean>;
  parent_event_id: XmlElem<number, EventCatalogDocumentTopElem>;
  course_finished: XmlElem<number>;
  course_process: XmlElem<number>;
  course_started: XmlElem<number>;
  course_began: XmlElem<number>;
  test_finished: XmlElem<number>;
  test_process: XmlElem<number>;
  test_started: XmlElem<number>;
  test_began: XmlElem<number>;
  group_formed: XmlElem<boolean>;
  course_id: XmlElem<number, CourseCatalogDocumentTopElem>;
  training_plan_id: XmlElem<number, TrainingPlanCatalogDocumentTopElem>;
  is_public: XmlElem<boolean>;
  is_open: XmlElem<boolean>;
  cost: XmlElem<number>;
  cost_type: XmlElem<string, typeof common.cost_types>;
  budget_period_id: XmlElem<number, BudgetPeriodCatalogDocumentTopElem>;
  distribute_cost_type: XmlElem<string>;
  duration_fact: XmlElem<number>;
  duration_days_fact: XmlElem<number>;
  mandatory_fill_response: XmlElem<boolean>;
  event_form: XmlElem<string, typeof lists.event_forms>;
  subdivision_id: XmlElem<number, SubdivisionCatalogDocumentTopElem>;
  org_id: XmlElem<number, OrgCatalogDocumentTopElem>;
  send_type: XmlElem<string>;
  send_persons_types: XmlElem<string>;
  group_educ_group_id: XmlElem<string>;
  webinar_system_id: XmlElem<number, WebinarSystemCatalogDocumentTopElem>;
  default_response_type_id: XmlElem<number, ResponseTypeCatalogDocumentTopElem>;
  tutor_main: XmlElem<string>;
  poll_id: XmlElem<number, PollCatalogDocumentTopElem>;
  role_id: XmlMultiElemObject<number>;
  notification_reminder_date: XmlElem<Date>;
  modification_date: XmlElem<Date>;
  app_instance_id: XmlElem<string>;
  OnBuild(): void;
  MatchDocTypeExt(): void;
  OnBuildExt(): void;
  OnDeleteExt(): void;
};
