type FactPaymentCatalogDocumentTopElem = XmlTopElem & {
  id: XmlElem<number>;
  name: XmlElem<string>;
  org_id: XmlElem<number, OrgCatalogDocumentTopElem>;
  client_org_id: XmlElem<number, OrgCatalogDocumentTopElem>;
  agent_org_id: XmlElem<number, OrgCatalogDocumentTopElem>;
  client_legal: XmlElem<string>;
  provider_legal: XmlElem<string>;
  agent_legal: XmlElem<string>;
  client_legal_name: XmlElem<string>;
  provider_legal_name: XmlElem<string>;
  agent_legal_name: XmlElem<string>;
  cost_currency_type_id: XmlElem<string, typeof lists.currency_types>;
  cost_value: XmlElem<number>;
  date: XmlElem<Date>;
  expense_id: XmlElem<number, ExpenseCatalogDocumentTopElem>;
  comment: XmlElem<string>;
  modification_date: XmlElem<Date>;
  OnBuild(): unknown;
};
