type PositionCommonCatalogDocumentTopElem = XmlTopElem & {
  id: XmlElem<number | null>;
  code: XmlElem<string | null>;
  name: XmlElem<string | null>;
  status: XmlElem<string | null, typeof common.position_common_statuss>;
  min_salary: XmlElem<number | null>;
  max_salary: XmlElem<number | null>;
  currency: XmlElem<string | null, typeof lists.currency_types>;
  position_familys: XmlElem<string | null>;
  allow_outstaff: XmlElem<boolean>;
  knowledge_parts: XmlElem<string | null>;
  tags: XmlElem<string | null>;
  experts: XmlElem<string | null>;
  kpi_profile_id: XmlElem<number | null, KpiProfileCatalogDocumentTopElem>;
  kpi_profiles_id: XmlMultiElemObject<number | null, KpiProfileCatalogDocumentTopElem>;
  bonus_profile_id: XmlElem<number | null, BonusProfileCatalogDocumentTopElem>;
  knowledge_profile_id: XmlElem<number | null, KnowledgeProfileCatalogDocumentTopElem>;
  parent_position_common_id: XmlMultiElemObject<number | null, PositionCommonCatalogDocumentTopElem>;
  grade_ids: XmlMultiElemObject<number | null, GradeCatalogDocumentTopElem>;
  modification_date: XmlElem<Date | null>;
  app_instance_id: XmlElem<string | null>;
  role_id: XmlMultiElemObject<number | null>;
  OnBuild(): void;
};
