type EventRoomCatalogDocumentTopElem = XmlTopElem &
EventCatalogBase &
AdminAccessBase & {
  id: XmlElem<number | null>;
  is_model: XmlElem<boolean>;
  use_vclass: XmlElem<boolean>;
  vclass_setting_id: XmlElem<number | null, VclassSettingCatalogDocumentTopElem>;
  conversation_id: XmlElem<number | null, ConversationCatalogDocumentTopElem>;
  compound_program_id: XmlElem<number | null, CompoundProgramCatalogDocumentTopElem>;
  education_program_id: XmlElem<number | null, EducationProgramCatalogDocumentTopElem>;
  education_method_id: XmlElem<number | null, EducationMethodCatalogDocumentTopElem>;
  create_compound_program_id: XmlElem<number | null, CompoundProgramCatalogDocumentTopElem>;
  place_id: XmlElem<number | null, PlaceCatalogDocumentTopElem>;
  vclass_host: XmlElem<string | null>;
  record_exists: XmlElem<boolean>;
  show_record: XmlElem<boolean>;
  parent_event_id: XmlElem<number | null, EventCatalogDocumentTopElem>;
  course_finished: XmlElem<number | null>;
  course_process: XmlElem<number | null>;
  course_started: XmlElem<number | null>;
  course_began: XmlElem<number | null>;
  test_finished: XmlElem<number | null>;
  test_process: XmlElem<number | null>;
  test_started: XmlElem<number | null>;
  test_began: XmlElem<number | null>;
  group_formed: XmlElem<boolean>;
  course_id: XmlElem<number | null, CourseCatalogDocumentTopElem>;
  training_plan_id: XmlElem<number | null, TrainingPlanCatalogDocumentTopElem>;
  is_public: XmlElem<boolean>;
  is_open: XmlElem<boolean>;
  cost: XmlElem<number | null>;
  cost_type: XmlElem<string | null, typeof common.cost_types>;
  budget_period_id: XmlElem<number | null, BudgetPeriodCatalogDocumentTopElem>;
  distribute_cost_type: XmlElem<string>;
  duration_fact: XmlElem<number | null>;
  duration_days_fact: XmlElem<number | null>;
  mandatory_fill_response: XmlElem<boolean>;
  event_form: XmlElem<string | null, typeof lists.event_forms>;
  subdivision_id: XmlElem<number | null, SubdivisionCatalogDocumentTopElem>;
  org_id: XmlElem<number | null, OrgCatalogDocumentTopElem>;
  send_type: XmlElem<string | null>;
  send_persons_types: XmlElem<string | null>;
  group_educ_group_id: XmlElem<string | null>;
  webinar_system_id: XmlElem<number | null, WebinarSystemCatalogDocumentTopElem>;
  tutor_main: XmlElem<string | null>;
  poll_id: XmlElem<number | null, PollCatalogDocumentTopElem>;
  role_id: XmlMultiElemObject<number | null>;
  modification_date: XmlElem<Date | null>;
  app_instance_id: XmlElem<string | null>;
  OnBuild(): void;
  MatchDocTypeExt(): void;
  OnBuildExt(): void;
  OnDeleteExt(): void;
};
