type PaCompetenceCatalogDocumentTopElem = XmlTopElem & {
  id: XmlElem<number | null>;
  pa_id: XmlElem<number | null, PaCatalogDocumentTopElem>;
  code: XmlElem<string | null>;
  name: XmlElem<string | null>;
  status: XmlElem<string | null, typeof common.assessment_appraise_participants>;
  assessment_appraise_id: XmlElem<number | null, AssessmentAppraiseCatalogDocumentTopElem>;
  event_id: XmlElem<number | null, EventCatalogDocumentTopElem>;
  person_id: XmlElem<number | null, CollaboratorCatalogDocumentTopElem>;
  person_fullname: XmlElem<string | null>;
  person_position_name: XmlElem<string | null>;
  expert_person_id: XmlElem<number | null, CollaboratorCatalogDocumentTopElem>;
  expert_person_fullname: XmlElem<string | null>;
  expert_person_position_name: XmlElem<string | null>;
  assessment_appraise_type: XmlElem<string | null, typeof common.assessment_appraise_types>;
  is_done: XmlElem<boolean>;
  competence_id: XmlElem<number | null, CompetenceCatalogDocumentTopElem>;
  plan: XmlElem<string | null>;
  mark: XmlElem<string | null>;
  weight: XmlElem<number>;
  modification_date: XmlElem<Date | null>;
  app_instance_id: XmlElem<string | null>;
  MatchDocTypeExt(): void;
  OnBuildExt(): void;
  OnDeleteExt(): void;
};
