type ExpertQuestionCatalogDocumentTopElem = XmlTopElem & {
  id: XmlElem<number | null>;
  code: XmlElem<string | null>;
  date: XmlElem<Date | null>;
  normative_date: XmlElem<Date | null>;
  answer_date: XmlElem<Date | null>;
  question: XmlElem<string | null>;
  person_id: XmlElem<number | null, CollaboratorCatalogDocumentTopElem>;
  person_fullname: XmlElem<string | null>;
  expert_id: XmlElem<number | null, ExpertCatalogDocumentTopElem>;
  status: XmlElem<boolean | null>;
  is_faq: XmlElem<boolean | null>;
  is_disclosed: XmlElem<boolean | null>;
  question_file_id: XmlElem<number | null, ResourceCatalogDocumentTopElem>;
  answer_file_id: XmlElem<number | null, ResourceCatalogDocumentTopElem>;
  knowledge_parts: XmlElem<string | null>;
  tags: XmlElem<string | null>;
  modification_date: XmlElem<Date | null>;
  app_instance_id: XmlElem<string | null>;
  OnBuild(): void;
};
