type ProjectCatalogDocumentTopElem = XmlTopElem &
AdminAccessBase & {
  id: XmlElem<number | null>;
  code: XmlElem<string | null>;
  name: XmlElem<string | null>;
  org_id: XmlElem<number | null, OrgCatalogDocumentTopElem>;
  subdivision_id: XmlElem<number | null, SubdivisionCatalogDocumentTopElem>;
  group_id: XmlElem<number | null, GroupCatalogDocumentTopElem>;
  contract_id: XmlElem<number | null, ContractCatalogDocumentTopElem>;
  project_type_id: XmlElem<number | null, ProjectTypeCatalogDocumentTopElem>;
  sale_contract_id: XmlElem<number | null, SaleContractCatalogDocumentTopElem>;
  status: XmlElem<string | null, typeof common.project_status_types>;
  is_model: XmlElem<boolean>;
  workflow_id: XmlElem<number | null, WorkflowCatalogDocumentTopElem>;
  plan_labor_costs: XmlElem<number | null>;
  fact_labor_costs: XmlElem<number | null>;
  percent_complete: XmlElem<number | null>;
  team_selected: XmlElem<boolean>;
  start_date_plan: XmlElem<Date | null>;
  end_date_plan: XmlElem<Date | null>;
  start_date_fact: XmlElem<Date | null>;
  end_date_fact: XmlElem<Date | null>;
  allow_assessment: XmlElem<boolean>;
  join_mode: XmlElem<string | null, typeof common.join_mode_types>;
  resource_type_id: XmlElem<number | null, ResourceTypeCatalogDocumentTopElem>;
  all_participant_view_task: XmlElem<boolean>;
  allow_assigning_tasks_to_all: XmlElem<boolean>;
  modification_date: XmlElem<Date | null>;
  app_instance_id: XmlElem<string | null>;
  role_id: XmlMultiElemObject<number | null>;
  OnBuild(): void;
};
