type PositionCatalogDocumentTopElem = XmlTopElem & {
  id: XmlElem<number | null>;
  code: XmlElem<string | null>;
  name: XmlElem<string | null>;
  org_id: XmlElem<number | null, OrgCatalogDocumentTopElem>;
  parent_object_id: XmlElem<number | null, SubdivisionCatalogDocumentTopElem>;
  basic_collaborator_id: XmlElem<number | null, CollaboratorCatalogDocumentTopElem>;
  basic_collaborator_fullname: XmlElem<string | null>;
  basic_rate: XmlElem<number | null>;
  is_boss: XmlElem<boolean>;
  position_date: XmlElem<Date | null>;
  position_finish_date: XmlElem<Date | null>;
  is_position_finished: XmlElem<boolean | null>;
  position_assignment_type: XmlElem<string | null, typeof common.position_assignment_types>;
  position_appointment_type_id: XmlElem<number | null, AppointmentTypeCatalogDocumentTopElem>;
  competence_profile_id: XmlElem<number | null, CompetenceProfileCatalogDocumentTopElem>;
  kpi_profile_id: XmlElem<number | null, KpiProfileCatalogDocumentTopElem>;
  kpi_profiles_id: XmlMultiElemObject<number | null, KpiProfileCatalogDocumentTopElem>;
  bonus_profile_id: XmlElem<number | null, BonusProfileCatalogDocumentTopElem>;
  knowledge_profile_id: XmlElem<number | null, KnowledgeProfileCatalogDocumentTopElem>;
  position_common_id: XmlElem<number | null, PositionCommonCatalogDocumentTopElem>;
  position_family_id: XmlElem<number | null, PositionFamilyCatalogDocumentTopElem>;
  staff_position_id: XmlElem<number | null, StaffPositionCatalogDocumentTopElem>;
  modification_date: XmlElem<Date | null>;
  app_instance_id: XmlElem<string | null>;
  OnBuild(): void;
};
