type PositionCatalogDocumentTopElem = XmlTopElem & {
  id: XmlElem<number>;
  code: XmlElem<string>;
  name: XmlElem<string>;
  org_id: XmlElem<number, OrgCatalogDocumentTopElem>;
  parent_object_id: XmlElem<number, SubdivisionCatalogDocumentTopElem>;
  basic_collaborator_id: XmlElem<number, CollaboratorCatalogDocumentTopElem>;
  basic_collaborator_fullname: XmlElem<string>;
  basic_rate: XmlElem<number>;
  is_boss: XmlElem<boolean>;
  position_date: XmlElem<Date>;
  position_finish_date: XmlElem<Date>;
  is_position_finished: XmlElem<boolean>;
  position_assignment_type: XmlElem<string, typeof common.position_assignment_types>;
  position_appointment_type_id: XmlElem<number, AppointmentTypeCatalogDocumentTopElem>;
  competence_profile_id: XmlElem<number, CompetenceProfileCatalogDocumentTopElem>;
  kpi_profile_id: XmlElem<number, KpiProfileCatalogDocumentTopElem>;
  kpi_profiles_id: XmlMultiElemObject<number, KpiProfileCatalogDocumentTopElem>;
  bonus_profile_id: XmlElem<number, BonusProfileCatalogDocumentTopElem>;
  knowledge_profile_id: XmlElem<number, KnowledgeProfileCatalogDocumentTopElem>;
  position_common_id: XmlElem<number, PositionCommonCatalogDocumentTopElem>;
  position_family_id: XmlElem<number, PositionFamilyCatalogDocumentTopElem>;
  staff_position_id: XmlElem<number, StaffPositionCatalogDocumentTopElem>;
  modification_date: XmlElem<Date>;
  app_instance_id: XmlElem<string>;
  OnBuild(): void;
};
