declare namespace tools_xshell {
  let uni_settings: XmlElem<unknown>;
  let dotnet_console: XmlElem<unknown>;
  let dotnet_env_ext: XmlElem<unknown>;
  let dotnet_auth: XmlElem<unknown>;
  let dotnet_utils: XmlElem<unknown>;
  function xshell(shell_params: string): unknown;
  function xshell_command(command: unknown, ocmd_params: unknown): unknown;
  function rebuild_catalogs(CmdParams: unknown): unknown;
  function rebuild_person_hierarchy(CmdParams: unknown): unknown;
  function list_packages(CmdParams: unknown): unknown;
  function process_packages(CmdParams: unknown): unknown;
  function get_application_type(): unknown;
  function get_application_info(CmdParams: unknown): unknown;
  function get_application_config(CmdParams: unknown): unknown;
  function set_application_config(CmdParams: unknown): unknown;
  function set_application_type(CmdParams: unknown): unknown;
  function set_database_config(CmdParams: unknown): unknown;
  function get_database_type(): unknown;
  function get_database_info(CmdParams: unknown): unknown;
  function get_database_config(CmdParams: unknown): unknown;
  function set_database_type(CmdParams: unknown): unknown;
  function get_database_provider(): unknown;
  function create_database(parsed_cmd_obj: unknown): unknown;
  function initialize_database(parsed_cmd_obj: unknown): unknown;
  function list_database_tasks(parsed_cmd_obj: unknown): unknown;
  function stop_database_task(parsed_cmd_obj: unknown): unknown;
  function migrate_database(parsed_cmd_obj: unknown): unknown;
  function get_current_domain(): unknown;
  function get_computer_name(): unknown;
  function console(value: unknown): unknown;
  function get_cmd_param_index(CmdParams: unknown, Key: unknown, KeyValue: unknown): unknown;
  function set_debug_mode(mode: unknown, turn_switch: unknown): unknown;
  function set_collect_mode(mode: unknown, turn_switch: unknown, args_switch: unknown, format: unknown, output: unknown, background: boolean): unknown;
  function list_components(CmdParams: unknown): unknown;
  function process_components(CmdParams: unknown): unknown;
  function delete_components(CmdParams: unknown): unknown;
}
