type DevelopmentPlanCatalogDocumentTopElem = XmlTopElem &
AdminAccessBase & {
  id: XmlElem<number | null>;
  code: XmlElem<string | null>;
  name: XmlElem<string | null>;
  assessment_appraise_id: XmlElem<number | null, AssessmentAppraiseCatalogDocumentTopElem>;
  assessment_plan_id: XmlElem<number | null, AssessmentPlanCatalogDocumentTopElem>;
  person_id: XmlElem<number | null, CollaboratorCatalogDocumentTopElem>;
  person_fullname: XmlElem<string | null>;
  person_position_name: XmlElem<string | null>;
  person_position_id: XmlElem<number | null, PositionCatalogDocumentTopElem>;
  person_position_parent_id: XmlElem<number | null, SubdivisionCatalogDocumentTopElem>;
  expert_person_id: XmlElem<number | null, CollaboratorCatalogDocumentTopElem>;
  expert_person_fullname: XmlElem<string | null>;
  expert_person_position_name: XmlElem<string | null>;
  expert_person_position_id: XmlElem<number | null, PositionCatalogDocumentTopElem>;
  expert_person_position_parent_id: XmlElem<number | null, SubdivisionCatalogDocumentTopElem>;
  department_id: XmlElem<number | null>;
  department_name: XmlElem<string | null>;
  custom_experts: XmlElem<string | null>;
  custom_experts_array: XmlMultiElemObject<number | null, CollaboratorCatalogDocumentTopElem>;
  is_custom_experts: XmlElem<boolean>;
  flag_appraise_department: XmlElem<boolean>;
  status: XmlElem<string | null, typeof common.assessment_appraise_participants>;
  assessment_appraise_type: XmlElem<string, typeof common.assessment_appraise_types>;
  is_done: XmlElem<boolean>;
  is_ready: XmlElem<boolean>;
  is_final: XmlElem<boolean>;
  flag_is_processed: XmlElem<boolean>;
  workflow_id: XmlElem<number | null, WorkflowCatalogDocumentTopElem>;
  workflow_state: XmlElem<string | null>;
  workflow_state_name: XmlElem<string | null>;
  workflow_state_last_date: XmlElem<Date | null>;
  is_workflow_init: XmlElem<boolean | null>;
  career_reserve_id: XmlElem<number | null, CareerReserveCatalogDocumentTopElem>;
  appraise_date: XmlElem<Date | null>;
  index: XmlElem<number | null>;
  modification_date: XmlElem<Date | null>;
  app_instance_id: XmlElem<string | null>;
  OnBuild(): void;
};
