declare namespace ms_tools {
  function get_url_from_catalog(sCatalogNameParam: string, iIDParam: number): unknown;
  function view_open_doc(sCatalogNameParam: string, iIDParam: number, TopElem: unknown): unknown;
  function view_delete_doc(_catalog_name: unknown): unknown;
  function raise_system_event(_code: unknown, _system_eventID: number, _objectDocID: number, _objectDoc: unknown): unknown;
  function raise_system_event_env(oSystemEventIDParam: unknown, oParams: unknown): unknown;
  let notes_var: XmlElem<unknown>;
  function notes_verify_password(_clear_password: unknown, _hash_password: unknown): unknown;
  function set_ui_lng(_ui_lng_id: number): unknown;
  function get_const(_ui_lng_id: number): unknown;
  function eval_column_const(_ui_lng_id: number): unknown;
  function eval_column_name(sCodeParam: string, ListElem: unknown): unknown;
  function obtain_ui_lngs(): unknown;
  function compare_versions(_version: unknown, _cur_version: unknown): unknown;
  function verify_disp_object_blocks(_doc_source: unknown): unknown;
  function delete_resource(oResourceParam: unknown): unknown;
  function delete_url_on_server(sUrl: string): unknown;
  function init_view(oSourceTarget: unknown): unknown;
  function get_log_email_errors(dtLastDateParam: Date): unknown;
  function get_border_panel_object(oBorderPanelParam: unknown): unknown;
  function open_dlg_global_settings(sSelTabParam: string): unknown;
  function check_doc_screen_access(TopElem: unknown): unknown;
  function check_access_block_rights(sAccessBlockParam: string, sRightParam: string, oUserParam: unknown): unknown;
  function obtain_shared_list_elem(sListPathParam: string, sPrimaryKeyParam: string, oListElemParam: unknown): unknown;
  function delete_shared_list_elem(sListPathParam: string, sPrimaryKeyParam: string): unknown;
  function save_cached_doc(docParam: Date): unknown;
  function trigger_onsavedoc(Doc: unknown): unknown;
  function check_std(teObjectParam: unknown): unknown;
  function list_edit_open_select(oListParam: unknown, oParams: unknown, oTarget: unknown): unknown;
  function get_columns_array_by_field(fldChild: unknown, arrColumns: unknown): unknown;
  function server_on_init(TopElem: unknown): unknown;
  function server_on_app_init(TopElem: unknown): unknown;
  function set_next_coding(teObjectTarget: unknown): unknown;
  function ask_options_activate_objects_to_persons(sTypeParam: string, arrValuesParam: unknown): unknown;
  function ask_options_activate_qualifications_to_persons(bAssignmentParam: boolean): unknown;
  function activate_objects_to_persons(sTaskIDParam: string, sType: string, sObjectIDs: string, sPersonIDs: string, oParams: unknown): unknown;
  function assign_qualifications_to_objects(sTaskIDParam: string, sType: string, sObjectIDs: string, oParams: unknown): unknown;
  function activate_to_objects(sTaskIDParam: string, sTypeParam: string, sObjectIDs: string, oParams: unknown): unknown;
  function check_task(sTaskIDParam: string, oRetTarget: unknown, Request: unknown): unknown;
  function init_task(oParams: unknown, iDelayParam: number): unknown;
  function init_task_data(teTaskInfo: unknown, iDelayParam: number): unknown;
  function start_task(sTaskIDParam: string, sMethodNameParam: string, oMethodParamsParam: unknown): unknown;
  function start_task_data(sTaskIDParam: string, sMethodNameParam: string, oMethodParamsParam: unknown): unknown;
  function get_task(sTaskIDParam: string): unknown;
  function get_task_data(sTaskIDParam: string): unknown;
  function set_task(sTaskIDParam: string, teTaskInfoParam: unknown): unknown;
  function set_task_data(sTaskIDParam: string, teTaskInfoParam: unknown): unknown;
  function get_tasks(sTaskListParam: string): unknown;
  function get_tasks_data(sTaskListParam: string): unknown;
  function set_task_field(sTaskIDParam: string, sFieldNameParam: string, sFieldValueParam: string): unknown;
  function set_task_field_data(sTaskIDParam: string, sFieldNameParam: string, sFieldValueParam: string): unknown;
  function remove_task(sTaskIDParam: string): unknown;
  function remove_task_data(sTaskIDParam: string): unknown;
  function set_message_task(sTaskIDParam: string, oParams: unknown): unknown;
  function return_message_task(sTaskIDParam: string, oParams: unknown): unknown;
  function show_massage_task(oTaskInfo: unknown): unknown;
  function start_task_progress(sMethodNameParam: string, oMethodParamsParam: unknown, oParamsParam: unknown): unknown;
  function recover_task_progress(): unknown;
  function set_progress_info(sTaskIDParam: string, oParams: unknown): unknown;
  function return_progress_info(sTaskIDParam: string, oParams: unknown): unknown;
  function catalog_resave(sTaskIDParam: string, sCatalogNameParam: string, bDataFlag: boolean, bIDFlag: boolean): unknown;
  function get_all_block_access_str(): unknown;
  function get_all_block_read_access_str(): unknown;
  function check_all_block_objects_access(sCatalogNameParam: string, sCanParam: string): unknown;
  function check_objects_access(sParentObjectsAccessParam: string, sCatalogNameParam: string, sCanParam: string): unknown;
  function check_access_blocks_by_catalog_name(sAccessBlocksParam: string, sCatalogNameParam: string, sCanParam: string): unknown;
  function check_user_by_catalog_name(oUserAccessParam: unknown, sCatalogNameParam: string, sCanParam: string): unknown;
  function check_cur_user_access_blocks_by_catalog_name(sCatalogNameParam: string, sCanParam: string): unknown;
  function check_cur_user_access_blocks(sAccessBlocParam: string, sCanParam: string): unknown;
  function check_cur_user_access_applications_by_catalog_name(sCatalogNameParam: string, curUser: unknown, oContentAccess: unknown, sCanElem: string): unknown;
  function get_admin_init_server_data(): unknown;
  function enable_logs_server(): unknown;
  function validate_blog_entry_comments(oObjectParam: unknown): unknown;
  function call_server_method(sLibNameParam: string, sMethodNameParam: string, arrParams: unknown): unknown;
  function exec_amgr_code(sScript: string): unknown;
  function navigate_view(sFrameParam: string, sUrlParam: string): unknown;
  function navigate_list(sUrlParam: string, sTypeParam: string): unknown;
  function get_view_url(sCatalogNameParam: string, sUrlQueryParam: string): unknown;
  function get_task_result_num(sResultParam: string): unknown;
  function get_callback_tasks(teRaram: unknown): unknown;
  function check_content_access(oContentAccessParam: unknown, sCatalogNameParam: string, iObjectIDParam: number, sAccessTypeParam: string): unknown;
  function save_doc_screen(TopElem: unknown): unknown;
  function set_view_templates(TopElem: unknown): unknown;
  function get_field_path(fldParam: unknown): unknown;
  function create_package_objects(fldPackage: unknown): unknown;
  function disp_block(sBlockNameParam: string): unknown;
  function create_resource_admin(sUrlParam: string, teSourceParam: unknown, Screen: unknown): unknown;
  function get_main_screen(): unknown;
  function get_loop_array(TopElem: unknown, List: unknown, bDispRoles: boolean, bDispFilter: boolean, bDispHier: boolean, arrSelRows: unknown, iParenIDParam: number, sSearchTypeParam: string, iRemoteCollectionIDParam: number, iStartPos: number, iPageSize: number): unknown;
  function navigate_access_block(sIDParam: string, sTypeParam: string, sScreenTypeParam: string): unknown;
  function get_access_block_items(fldAccessBlockParam: unknown): unknown;
  function set_cur_user_content_first_catalog_url(sTabBlockTypeParam: string, iObjectIDParam: number): unknown;
  function binary_load_from_url(fldTarget: unknown, sUrlParam: string, b64encode: boolean): unknown;
  function run_view_action(TopElem: unknown, oScreenParam: unknown, sGridItemNameParam: string): unknown;
  function convert_exec_code(fldExecTarget: unknown, fldUrlTarget: unknown, fldTextTarget: unknown): unknown;
  function convert_host_auth(TopElem: unknown): unknown;
  function foreign_elem_title(fldSource: unknown, sFieldNameParam: string, sDefauldTextParam: string): unknown;
  let menu_arrs_env: XmlElem<unknown>;
  function get_menu_blocks(): unknown;
  function get_object_source_server(iObjectIDParam: number): unknown;
  function calculate_statistic_rec_obj(iStatisticRecIDParam: number, iObjectIDParam: number, iPersonIDParam: number): unknown;
  function evaluate_remote_collection_obj(oRemoteCollectionParam: unknown, iObjectIDParam: number, iPersonIDParam: number, oCollectionParams: unknown, iStartPos: number, iPageSize: number): unknown;
  function eval_menu_remote_action(oList: unknown, ListElemAction: unknown, oScreenParam: unknown): unknown;
  function eval_remote_action_step(iRemoteActionIDParam: number, oParamsParam: unknown): unknown;
  function eval_remote_action(oRemoteActionIDParam: unknown, oParamsParam: unknown, fldTopElemParam: unknown, oScreenParam: unknown, sDispTypeParam: string): unknown;
  function get_remote_actions_by_cur_application(sCatalogNameParam: string, iViewConfigurationID: number): unknown;
  function get_element_property(oElem: unknown, sPropertyName: string, sAltPropertyName: string): unknown;
  function disp_application_view_configuration(teApplicationParam: unknown, sViewConfigurationIDParam: string, sElemType: string, oMenuElem: unknown, bNoTab: boolean, bOnlyUrl: boolean): unknown;
  function disp_application_complex_block(sBlockIDParam: string, bNoTab: boolean, bOnlyUrl: boolean): unknown;
  function update_access_blocks_doc_types(fldAccessBlocks: unknown): unknown;
  function update_claims_by_object(oObjectID: number, sObjectType: string, sClaimTypes: string): unknown;
  function get_doc_screen_wvars(oDocParam: unknown): unknown;
}
