type DnStudentCatalogDocumentTopElem = XmlTopElem &
AdminAccessBase & {
  id: XmlElem<number>;
  code: XmlElem<string>;
  type: XmlElem<string, typeof common.stud_types>;
  person_id: XmlElem<number, CollaboratorCatalogDocumentTopElem>;
  person_fullname: XmlElem<string>;
  email: XmlElem<string>;
  phone: XmlElem<string>;
  region: XmlElem<string>;
  adress_fact_live: XmlElem<string>;
  special_id: XmlElem<number, DnSpecialCatalogDocumentTopElem>;
  specialization_id: XmlElem<number, DnSpecializationCatalogDocumentTopElem>;
  educat_form_id: XmlElem<string, DnEducatFormCatalogDocumentTopElem>;
  edu_condition_id: XmlElem<string, DnEduConditionCatalogDocumentTopElem>;
  qualification_id: XmlElem<number, QualificationCatalogDocumentTopElem>;
  status_id: XmlElem<string, typeof common.student_states>;
  main_group_id: XmlElem<number, DnStudGroupCatalogDocumentTopElem>;
  educat_groups: XmlElem<string>;
  stud_dt_id: XmlElem<string, typeof common.stud_doc_types>;
  educat_institution: XmlElem<string>;
  is_excellent: XmlElem<boolean>;
  faculty_id: XmlElem<number, SubdivisionCatalogDocumentTopElem>;
  chair_id: XmlElem<number, SubdivisionCatalogDocumentTopElem>;
  scient_adviser_id: XmlElem<number, LectorCatalogDocumentTopElem>;
  subject: XmlElem<string>;
  file_name: XmlElem<string>;
  modification_date: XmlElem<Date>;
  app_instance_id: XmlElem<string>;
  OnBuild(): unknown;
};
