type FuncManagerCatalogDocumentTopElem = XmlTopElem & {
  id: XmlElem<number | null>;
  catalog: XmlElem<string | null, typeof common.exchange_object_types>;
  object_id: XmlElem<number | null>;
  object_name: XmlElem<string | null>;
  subordinate_position_id: XmlElem<number | null, PositionCatalogDocumentTopElem>;
  person_id: XmlElem<number | null, CollaboratorCatalogDocumentTopElem>;
  person_fullname: XmlElem<string | null>;
  person_position_id: XmlElem<number | null, PositionCatalogDocumentTopElem>;
  staff_object_type: XmlElem<string | null, typeof common.exchange_object_types>;
  staff_object_id: XmlElem<number | null>;
  staff_object_name: XmlElem<string | null>;
  is_native: XmlElem<boolean>;
  boss_type_id: XmlElem<number | null, BossTypeCatalogDocumentTopElem>;
  start_date: XmlElem<Date | null>;
  end_date: XmlElem<Date | null>;
  is_finished: XmlElem<boolean | null>;
  parent_id: XmlElem<number | null, SubdivisionCatalogDocumentTopElem>;
  org_id: XmlElem<number | null, OrgCatalogDocumentTopElem>;
  MatchDocTypeExt(): void;
  OnBuildExt(): void;
  OnDeleteExt(): void;
};
