type StatementCatalogDocumentTopElem = XmlTopElem & {
  id: XmlElem<number | null>;
  code: XmlElem<string | null>;
  name: XmlElem<string | null>;
  create_date: XmlElem<Date | null>;
  create_ticks: XmlElem<number | null>;
  timestamp: XmlElem<Date | null>;
  statement_ref_id: XmlElem<string | null>;
  voided: XmlElem<boolean>;
  processed: XmlElem<boolean | null>;
  learning_storage_id: XmlElem<number | null, LearningStorageCatalogDocumentTopElem>;
  person_id: XmlElem<number | null, CollaboratorCatalogDocumentTopElem>;
  person_fullname: XmlElem<string | null>;
  object_id: XmlElem<number | null>;
  object_type: XmlElem<string | null, typeof common.exchange_object_types>;
  object_name: XmlElem<string | null>;
  activity_id: XmlElem<number | null, ActivityCatalogDocumentTopElem>;
  activity_code: XmlElem<string | null>;
  verb_id: XmlElem<string | null>;
  verb_name: XmlElem<string | null>;
  agent_json_str: XmlElem<string | null>;
  registration: XmlElem<string | null>;
  context_registration: XmlElem<string | null>;
  context_instructor: XmlElem<string | null>;
  context_team: XmlElem<string | null>;
  context_revision: XmlElem<string | null>;
  context_platform: XmlElem<string | null>;
  context_language: XmlElem<string | null>;
  context_statement: XmlElem<string | null>;
  result_score_max: XmlElem<number | null>;
  result_score_min: XmlElem<number | null>;
  result_score_raw: XmlElem<number | null>;
  result_score_scaled: XmlElem<number | null>;
  result_success: XmlElem<boolean | null>;
  result_completion: XmlElem<boolean | null>;
  result_response: XmlElem<string | null>;
  result_duration: XmlElem<string | null>;
  modification_date: XmlElem<Date | null>;
  app_instance_id: XmlElem<string | null>;
  OnBuild(): void;
};
